WEB/Controllers/ArticleController.cs
using AutoMapper;
using BLL.DTO;
using BLL.Infrastructure;
using BLL.Interfaces;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEB.Mappers;
using WEB.Models;
using WEB.Pagination;

namespace WEB.Controllers
{
    public class ArticleController : Controller
    {
        readonly IArticleService articleService;
        private readonly IMapper mapper;

        public ArticleController(IArticleService serv, IMapper map)
        {
            articleService = serv;
            mapper = map;
        }

        /// <summary>
        /// Show information about all Article.
		/// <param name="searchTitle">Specifies what text should be included in the title of Articles.</param>
		/// <param name="searchText">Specifies what text should be included in the text of articles</param>
		/// <param name="tags">Indicates which tag the article should have.</param>	
        /// <param name="sorting">Indicates on what basis to sort.</param>
		/// <param name="page">Number page of articles for pagination</param>
		/// <returns>View with articles.</returns>
        [Authorize(Roles = "admin")]
        public async Task<ActionResult> ArticlesAdmin(string searchTitle, string searchText, string tags, Sort? sorting, int page = 1)
        {
            ViewBag.searchTitle = searchTitle;
            ViewBag.searchText = searchText;
            ViewBag.sorting = sorting;
            if (tags == "System.Collections.Generic.List`1[BLL.DTO.TagDTO]")
                tags = null;
            ViewBag.tag = tags;
            IEnumerable<ArticleDTO> articleDTO;
            articleDTO = await articleService.GetAllIsDeleteAsync(searchTitle, searchText, tags, sorting);

            ViewBag.Tags = await articleService.GetAllTagsAsync();
            var article = mapper.Map<IEnumerable<ArticleDTO>, List<ArticleModel>>(articleDTO);
            int pageSize = 6;
            IEnumerable<ArticleModel> articlesPerPages = article.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = article.Count };
            IndexViewModel<ArticleModel> ivm = new IndexViewModel<ArticleModel> { PageInfo = pageInfo, Models = articlesPerPages };
            return View("ArticlesAdmin", ivm);
        }

        /// <summary>
        /// Show information about all Article.
        /// <param name="searchTitle">Specifies what text should be included in the title of Articles.</param>
        /// <param name="searchText">Specifies what text should be included in the text of articles</param>
        /// <param name="tags">Indicates which tag the article should have.</param>	
        /// <param name="sorting">Indicates on what basis to sort.</param>
        /// <param name="page">Number page of articles for pagination</param>
        /// <returns>View with articles.</returns>
        public async Task<ActionResult> Index(string id, string searchTitle, string searchText, string tags, Sort? sorting, int page = 1)
        {
            ViewBag.searchTitle = searchTitle;
            ViewBag.searchText = searchText;
            ViewBag.sorting = sorting;
            if (tags == "System.Collections.Generic.List`1[BLL.DTO.TagDTO]")
                tags = null;
            ViewBag.tag = tags;
            IEnumerable<ArticleDTO> articleDTO;
            int pageSize = 3;
            if (!(id is null))
            {
                articleDTO = await articleService.GetAllByUserIdIsDeleteAsync(id, searchTitle, searchText, tags, sorting);

            }
            else
            {
                articleDTO = await articleService.GetAllIsDeleteAsync(searchTitle, searchText, tags, sorting);
            }

            ViewBag.Tags = await articleService.GetAllTagsAsync();
            var article = mapper.Map<IEnumerable<ArticleDTO>, List<ArticleModel>>(articleDTO);

            IEnumerable<ArticleModel> articlesPerPages = article.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = article.Count };
            IndexViewModel<ArticleModel> ivm = new IndexViewModel<ArticleModel> { PageInfo = pageInfo, Models = articlesPerPages };

            return View(ivm);
        }


        /// <summary>
        /// Show information about exact Article.
        /// </summary>
        /// <param name="id">Id of Article.</param>
        /// <param name="page">Number page of coments for pagination</param>
        /// <returns>View with information about exact Article and its comments.</returns>
        public async Task<ActionResult> Details(int? id, int page = 1)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleDTO articleDTO = await articleService.GetItemAsync(id);
            if (articleDTO == null)
            {
                return HttpNotFound();
            }
            var article = mapper.Map<ArticleDTO, ArticleModel>(articleDTO);
            ViewBag.Tags = await articleService.GetAllTagsAsync();

            //ViewBag.ChangedateArticle = await articleService.GetLastChangeArticleByIdAsync(article.Id);
            var comment = mapper.Map<IEnumerable<CommentDTO>, IEnumerable<CommentModel>>(articleDTO.Comments);
            ViewBag.CountComment = comment.Count();
            if (comment.Count() == 0)
            {
                comment = new List<CommentModel> { new CommentModel { Article = article, UserProfile = article.UserProfile, ArticleId = article.Id, ProfileId = article.ProfileId } };
                ViewBag.CountComment = 0;
            }

            int pageSize = 5;
            IEnumerable<CommentModel> comentPerPages = comment.Skip((page - 1) * pageSize).Take(pageSize);
            PageInfo pageInfo = new PageInfo { PageNumber = page, PageSize = pageSize, TotalItems = comment.Count() };
            IndexViewModel<CommentModel> ivm = new IndexViewModel<CommentModel> { PageInfo = pageInfo, Models = comentPerPages };
            return View(ivm);
        }

        /// <summary>
        /// Show create form.
        /// </summary>
        /// <returns>View with create form.</returns>
        public async Task<ActionResult> Create()
        {
            ViewBag.Blogs = await GetBlogsByUser(User.Identity.GetUserId());

            var allTags = await articleService.GetAllTagsAsync();
            var article = new ArticleModel();
            article.TagsName = new Dictionary<string, bool>();
            allTags.ToList().ForEach(s => article.TagsName.Add(s.Title, false));

            return View(article);
        }

        /// <summary>
        /// Receives data about the article using the post method and create the article in system
        /// </summary>
        /// <param name="articleModel">Form with article data.</param>
        /// <param name="uploadImage">Upload image - main image for article..</param>
        /// <returns>Redirect to Action Index .</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,IsDelete, IsAvatar, BlogId, Text, TagsName")] ArticleModel articleModel, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                List<TagDTO> tags = new List<TagDTO>();
                foreach (var tag in articleModel.TagsName)
                {
                    if (tag.Value)
                    {
                        tags.Add(new TagDTO { Title = tag.Key });
                    }
                }
                articleModel.Tags = tags;
                articleModel.TagsName = null;
                articleModel.DateTime = DateTime.Now;
                var usId = User.Identity.GetUserId();
                articleModel.ProfileId = usId;

                var article = mapper.Map<ArticleModel, ArticleDTO>(articleModel);
                if (uploadImage != null)
                    article.IsAvatar = true;
                await articleService.AddItemAsync(article);
                if (uploadImage != null)
                {
                    var allArtcleByUser = await articleService.GetAllByUserIdAsync(usId, null, null, null, null);
                    int aId  = allArtcleByUser.First().Id ;
                    var fileName = Path.GetFileName(usId + "_" + aId + ".jpg");
                    var path = Path.Combine(Server.MapPath("~/Content/img/articles/"), fileName);
                    uploadImage.SaveAs(path);          
                }

                return RedirectToAction("Index");
            }

            return View(articleModel);
        }

        /// <summary>
        /// Show edit form.
        /// </summary>
        /// <param name="id">Id of Article.</param>
        /// <returns>View with edit form , or return  form with errors.</returns>
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArticleDTO articleDTO = await articleService.GetItemAsync(id);
            if (articleDTO == null)
            {
                return HttpNotFound();
            }
            if (articleDTO.ProfileId == User.Identity.GetUserId() || User.IsInRole("admin"))
            {
                var article = mapper.Map<ArticleDTO, ArticleModel>(articleDTO);
                var allTags = await articleService.GetAllTagsAsync();
                article.TagsName = new Dictionary<string, bool>();
                var isTag = false;
                foreach (var item in allTags)
                {
                    isTag = false;
                    foreach (var i in article.Tags)
                    {
                        if (item.Title == i.Title)

WEB/Views/Article/ArticlesAdmin.cshtml
@model WEB.Pagination.IndexViewModel<WEB.Models.ArticleModel>
@using WEB.Helpers
@using BLL.Infrastructure

@{
    ViewBag.Title = "ArticlesAdmin";
}

<div class="col-3-3" id="post-container">
    <div class="wrap-col">
        <div class="post">
            <div class="post-margin">

                <h2>All Articles</h2>
                <table class="table">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().IsAvatar)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().DateTime)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().Text)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().Blog.Title)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Models.FirstOrDefault().UserProfile.Name)
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in Model.Models)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IsAvatar)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DateTime)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Text)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Blog.Title)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UserProfile.Name)
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                @Html.ActionLink("Detail", "Details", new { id = item.Id }) |
                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                            </td>
                        </tr>
                    }

                </table>
                @Html.PageLinks(Model.PageInfo, x => Url.Action("ArticlesAdmin", new { page = x, searchTitle = @ViewBag.searchName, sarchText = ViewBag.searchText, tags = ViewBag.tag, sorting = ViewBag.sorting }))

            </div>
        </div>
    </div>
</div>

WEB/Views/Article/Create.cshtml
@model WEB.Models.ArticleModel

@{
    ViewBag.Title = "Create";
}

<!-- Start Posts Container -->
<div class="col-3-3" id="post-container">
    <div class="wrap-col">
        <div class="post">
            <div class="post-margin">
                @if (ViewBag.Blogs.Items.Count != 0)
                {
                    <h3>Create new article</h3>

                    using (Html.BeginForm("Create", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">

                            @Html.HiddenFor(model => model.ProfileId)
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>




                            <div class="form-group">
                                @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                                </div>
                            </div>



                            <div class="form-group">
                                @Html.Label("Blog title", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(model => model.BlogId, ViewBag.Blogs as SelectList, new { @class = "form-control", style = "max-width:100% !important;" })
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-10">

                                    @Html.Label("Select tags to add", htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">

                                        @foreach (var tag in Model.TagsName)
                                        {
                                            <label for="sem-@tag.Key">@tag.Key</label>
                                            @Html.CheckBoxFor(model => model.TagsName[tag.Key], new { @class = "my-sem", @id = "sem-" + tag.Key })
                                        }
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="editor-field">
                                        <input type="file" name="uploadImage" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Create" class="btn btn-default" id="IsAvatar" />
                                </div>
                            </div>
                        </div>
                    }

                    <div>
                        @Html.ActionLink("Back to List", "Index")
                    </div>
                }
                else
                {
                    <h4>You haven`t any bogs!</h4>
                    <h4>If you want to creat new blog click @Html.ActionLink("here", "Create", "Blog")</h4>
                }

                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>
<!-- End Posts Container -->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WEB/Views/Article/DeleteComment.cshtml
@model WEB.Models.CommentModel

@{
    ViewBag.Title = "DeleteComment";
}

<h2>DeleteComment</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayName("Article title")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Article.Title)
        </dd>



    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to article", "Details", new { id = Model.ArticleId})
        </div>
    }
</div>

WEB/Views/Article/Edit.cshtml
@model WEB.Models.ArticleModel

@{
    ViewBag.Title = "Edit";
}

<!-- Start Posts Container -->
<div class="col-3-3" id="post-container">
    <div class="wrap-col">


        <div class="post">
            <div class="post-margin">

                @using (Html.BeginForm("Edit", "Article", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Edit Article @Model.Title</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.ProfileId)

                <div class="form-group">
                      @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                          @Html.EditorFor(model => @model.Title, new { htmlAttributes = new { @class = "form-control" } }) 
                        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                    </div>
                </div>




                    <div class="form-group">
                        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <div class="form-group">
                        @Html.Label("Blog title", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.BlogId, ViewBag.Blogs as SelectList, new { @class = "form-control", style = "max-width:100% !important;" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-10">

                            @Html.Label("Select tags to add", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">

                                @foreach (var tag in Model.TagsName)
                                {
                                    <label for="sem-@tag.Key">@tag.Key</label>
                                    @Html.CheckBoxFor(model => model.TagsName[tag.Key], new { @class = "my-sem", @id = "sem-" + tag.Key })
                                }
                            </div>
                        </div>
                    </div>



                    <div class="form-group">
                        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="editor-field">
                                <input type="file" name="uploadImage" />
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>
                }

                <div>
                    @Html.ActionLink("Back to List", "Index")|
                    @Html.ActionLink("Back to article", "Details/", new { @id = Model.Id })
                </div>

                <div class="clear"></div>
            </div>
        </div>
    </div>
    <!-- End Posts Container -->
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WEB/Views/Article/Index.cshtml
@model WEB.Pagination.IndexViewModel<WEB.Models.ArticleModel>
@using WEB.Helpers
@using BLL.Infrastructure


@using Microsoft.AspNet.Identity;

@{
    ViewBag.Title = "Index";
}

<!-- Start Posts Container -->
<div class="col-2-3" id="post-container">

    <div class="wrap-col">

        @if ((User.Identity.IsAuthenticated) || User.IsInRole("admin"))
        {
            <div class="post">
                <div class="link">@Html.ActionLink("Create new Article", "Create")</div>
            </div>
        }


        @foreach (var item in Model.Models)
        {

            <!-- Start Post Item -->
            <div class="post">
                <div class="post-margin">
                    <div class="post-avatar">
                        <div class="avatar-frame"></div>

                        @if ((item.UserProfile.Avatar == "") || (item.UserProfile.Avatar is null))
                        {
                            <img src="@Url.Content("~/Content/img/users/avatar.jpg")" />
                        }
                        else
                        {
                            <img src="@Url.Content("~/Content/img/users/"+item.UserProfile.Avatar)" alt="avatar" class='my-avatar-article ' />
                        }


                    </div>

                    <h4 class="post-title">
                        @Html.ActionLink(@item.Title, "Details/", new { @id = item.Id }, new { @class = "readmore" })
                    </h4>
                    <ul class="post-status">
                        <li>
                            <i class="fa fa-clock-o"></i>@item.DateTime
                        </li>
                        <li>
                            <i class="fa fa-folder-open-o"></i>
                            @Html.ActionLink(@item.UserProfile.Name, "Info", "Account", new { id = @item.UserProfile.Id }, new { @title = "View profile " + @item.UserProfile.Name, @rel = "category" })

                        </li>
                        <li>
                            <i class="fa fa-folder-open-o"></i>
                            @Html.ActionLink(@item.Blog.Title, "Details", "Blog", new { id = @item.BlogId }, new { @title = "View all posts in blog " + @item.Blog.Title, @rel = "category" })

                        </li>
                        <li>
                            <i class="fa fa-comment-o"><a href="#" rel="category">@item.Comments.Count</a></i>

                        </li>
                    </ul>
                    <div class="clear"></div>
                </div>

                <div class="featured-image">
                    @if (!(item.IsAvatar))
                    {
                        <img src="@Url.Content("~/Content/img/articles/img.jpg")" />
                    }
                    else
                    {
                        <img src="@Url.Content("~/Content/img/articles/"+item.ProfileId + "_"+ item.Id + ".jpg")" alt="img" class='attachment-post-standard ' />
                    }
                    <div class="post-icon">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-pencil fa-stack-1x fa-inverse"></i>
                        </span>
                    </div>
                </div>

                <div class="post-margin-text">
                    <p>
                        @item.Text
                    </p>
                </div>

                <!-- Post Tags -->
                @if (item.Tags.Count != 0)
                {


                    <div class="post-tags">
                        <span class="fa-stack fa-lg">
                            <i class="fa fa-circle fa-stack-2x"></i>
                            <i class="fa fa-tags fa-stack-1x fa-inverse"></i>
                        </span>
                        @foreach (var tag in item.Tags)
                        {
                            <span>    #</span>
                            @Html.ActionLink(@tag.Title, "Index", new { tag = "@tag.Title" })
                        }
                    </div>
                    <div class="clear"></div>
                }
                <!-- End Post Tags -->

                <ul class="post-social">
                    <li>
                        @Html.ActionLink("Read More", "Details/", new { @id = item.Id }, new { @class = "readmore" })
                    </li>
                </ul>

                <div class="clear"></div>
            </div>
            <!-- End Post Item -->

        }






        <!-- Start Pagination -->
        <div class="spacing-20"></div>

        @Html.PageLinks(Model.PageInfo, x => Url.Action("Index", new { page = x, searchTitle = @ViewBag.searchName, sarchText = ViewBag.searchText, tags = ViewBag.tag, sorting = ViewBag.sorting }))

        <!-- End Pagination -->
        <div class="clear"></div>
    </div>
</div>


<!-- Start Sidebar -->
<div class="col-1-3">
    <div class="wrap-col">
        <div class="widget-container">
            <form role="search" method="get" id="searchform" class="searchform" action="">
                <div>
                    <label class="screen-reader-text" for="searchTitle">Search for title:</label>
                    <input type="text" value="" name="searchTitle" id="s" />
                    <input type="submit" id="searchsubmit" value="🔍︎" />
                </div>
            </form><div class="clear"></div>

            <form role="search" method="get" id="searchform" class="searchform" action="">
                <div>
                    <label class="screen-reader-text" for="searchText">Search for text:</label>
                    <input type="text" value="" name="searchText" id="s" />
                    <input type="submit" id="searchsubmit" value="🔍︎" />
                </div>
            </form>
            <div class="clear"></div>
        </div>

        <div class="widget-container">

            <ul>
                @*<ul class="sf-menu pos-center">*@


                <li class="menu-item">
                    <label class="screen-reader-text">Sort articles:</label>
                    <ul class="sub-menu">
                        <li class="menu-item-sort">
                            Sort by Title 
                            @Html.ActionLink("🡅", "Index", "Article", new { sorting = Sort.TitleAsc, searchTitle = @ViewBag.searchTitle, sarchText = ViewBag.searchText, tags = ViewBag.tag }, null)
                            @Html.ActionLink("🡇", "Index", "Article", new { sorting = Sort.TitleDesc, searchTitle = @ViewBag.searchTitle, sarchText = ViewBag.searchText, tags = ViewBag.tag }, null)

                        </li>
                        <li class="menu-item">
                            Sort by Date
                            @Html.ActionLink("🡅", "Index", "Article", new { sorting = Sort.DateAsc, searchTitle = @ViewBag.searchTitle, sarchText = ViewBag.searchText, tags = ViewBag.tag }, null)
                            @Html.ActionLink(" 🡇", "Index", "Article", new { sorting = Sort.DateDesc, searchTitle = @ViewBag.searchTitle, sarchText = ViewBag.searchText, tags = ViewBag.tag }, null)
                        </li>


                    </ul>
                </li>
            </ul>

            <div class="clear"></div>
        </div>

        <div class="widget-container">
            <h6 class="widget-title">Tag Cloud</h6>
            <div class="tagcloud">
                <form role="search" method="get" id="searchform" class="searchform" action="">
                    <div>
                        @foreach (var tag in ViewBag.Tags)
                        {
                            <input type="submit" id="searchsubmit" value=@tag.Title name="tags" class='tag-link-12 my-tag' />
                        }
                    </div>
                </form>
            </div>
            <div class="clear"></div>
        </div>

        <div class="clear"></div>
    </div>
</div>        <!-- End Sidebar -->

<div class="clear"></div>